language: python

os: linux

sudo: required

services:
  - docker

before_install:
  - if [[ "$RUN_DOCKER" == "yes" ]]; then docker pull iotjs/js_remote_test:0.6; fi

install:
  - pip install pylint

script: "tools/travis_script.py $OPTS"

env:
  matrix:
    - OPTS="--device=artik530 --app=iotjs" RUN_DOCKER=yes
